### ISSUE TITLE
breaking in postgres

### ISSUE THREAD

**Issue by mithucste30** [Faveod/arel-extensions#26]
I had to downgrade all the way to 1.2.0 to make it work, after that all the verison is breaking queries in postgresql

```code
rb(main):001:0> User.last.top_providers
  User Load (1.0ms)  SELECT
    "users" . *
  FROM
    "users"
  ORDER BY
    "users" . "id" DESC LIMIT 1
  Provider Load (0.4ms)  SELECT
    "providers" . *
    ,"user_provider_interests" . "points" AS "interest_points"
  FROM
    "providers" LEFT OUTER JOIN "user_provider_interests" (
        ON "user_provider_interests" . "provider_id" = "providers" . "id"
    )
    AND (
      "user_provider_interests" . "user_id" = 89231
    )
  ORDER BY
    "user_provider_interests" . "points" DESC
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "ON"
LINE 1: ...iders" LEFT OUTER JOIN "user_provider_interests" (ON "user_p...
                                                             ^
: SELECT "providers".*, "user_provider_interests"."points" AS "interest_points" FROM "providers" LEFT OUTER JOIN "user_provider_interests" (ON "user_provider_interests"."provider_id" = "providers"."id") AND ("user_provider_interests"."user_id" = 89231)  ORDER BY "user_provider_interests"."points" DESC
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
	from /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/querying.rb:39:in `find_by_sql'
	from /usr/local/bundle/gems/bullet-6.1.0/lib/bullet/active_record42.rb:26:in `find_by_sql'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/relation.rb:639:in `exec_queries'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/relation.rb:515:in `load'
	from /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/relation.rb:243:in `to_a'
... 3 levels...
	from /usr/local/bundle/gems/railties-4.2.11.1/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/bundle/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/bundle/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /usr/src/app/bin/rails:9:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by jdelporte** [comment]
Hi and thanks you for the feedback,
To  reproduct and correct this bug, we will need to see how the query is construct. Can you show us the code of the method top_providers  ? and if it is an association can you show us its defintion ?

**Comment by mithucste30** [comment]
@jdelporte sure

```code

Provider
        .select(Provider.arel_table[Arel.star])
        .select(User::ProviderInterest.arel_table[:points].coalesce(0).as('interest_points'))
        .joins(top_provider_associations)
        .order(User::ProviderInterest[:points].desc)

**Comment by mithucste30** [comment]
Update in other places today I had to downgrade even further to[1.8.0] make working, where i was using common table expression[CTE]

this part of the query was breaking, which is a part of a big large query

```code
Collection
            .active
            .select('collections.*')
            .select("string_agg(DISTINCT tags.name, ',') AS tag_names")
            .select("c_categories.name AS category_name")
            .select("admins.email AS creator_email")
            .select("string_agg(concat(audio_clips.duration_int::varchar, '-', audio_clips.id::varchar), ',') AS durations")
            .select("count(DISTINCT audio_clips) AS clips_count")
            .select("count(DISTINCT nl_clips) AS not_listened_clips_count")
            .select('case when count(nl_clips) > 0
                               then true
                               else false
                          end AS highlighted')
            .left_join(:creator)
            .joins(:category)
            .joins("INNER JOIN categories c_categories ON collections.category_id = c_categories.id")
            .group('collections.id, c_categories.name, admins.email')
            .joins("LEFT JOIN audio_clips nl_clips ON nl_clips.id = audio_clips.id AND
                                                      nl_clips.id NOT IN (select audio_clip_id
                                                                          from audio_clips_users
                                                                          where user_id = #{@user_id})")
```

this error appeared

```code
Completed 500 Internal Server Error in 590ms (ActiveRecord: 36.3ms)

ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  syntax error at or near ":"
LINE 20:       concat( audio_clips.duration_int : : VARCHAR ,'-' ,aud...
                                                ^
: WITH "categories_with_points" AS (SELECT
    "categories" . "id"
    ,MAX( COALESCE ( uci.points ,0 ) ) AS points
  FROM
    "categories" LEFT OUTER JOIN user_category_interests uci
      ON categories.id = uci.category_id
    AND uci.user_id = 51021
  GROUP BY
    "categories" . "id"
  ORDER BY
    2 DESC), "valid_collections" AS (SELECT
    DISTINCT collections. *
    ,string_agg (
      DISTINCT tags.name
      ,','
    ) AS tag_names
    ,c_categories.name AS category_name
    ,admins.email AS creator_email
    ,string_agg (
      concat( audio_clips.duration_int : : VARCHAR ,'-' ,audio_clips.id : : VARCHAR )
      ,','
    ) AS durations
    ,COUNT( DISTINCT audio_clips ) AS clips_count
    ,COUNT( DISTINCT nl_clips ) AS not_listened_clips_count
    ,CASE
      WHEN COUNT( nl_clips ) > 0
      THEN TRUE
      ELSE FALSE
    END AS highlighted
  FROM
    "collections" INNER JOIN "collection_tags"
      ON "collection_tags" . "collection_id" = "collections" . "id" INNER JOIN "tags"
      ON "tags" . "id" = "collection_tags" . "tag_id" INNER JOIN "taggings"
      ON "taggings" . "tag_id" = "tags" . "id" INNER JOIN "audio_clips"
      ON "audio_clips" . "id" = "taggings" . "audio_clip_id" INNER JOIN "categories"
      ON "categories" . "id" = "collections" . "category_id" LEFT OUTER JOIN "admins"
      ON "admins" . "id" = "collections" . "admin_id" INNER JOIN categories c_categories
      ON collections.category_id = c_categories.id LEFT JOIN audio_clips nl_clips
      ON nl_clips.id = audio_clips.id
    AND nl_clips.id NOT IN (
      SELECT
          audio_clip_id
        FROM
          audio_clips_users
        WHERE
          user_id = 51021
    )
  WHERE
    "audio_clips" . "published" = 't'
    AND (
      audio_clips.publish_time < '2020-06-26 11:31:34'
    )
    AND (
      audio_clips.expires_at > '2020-06-26 11:31:34'
    )
    AND (
      (
        audio_clips.clip_type = 'magazine'
        AND audio_clips.publish_time > '2020-06-19 11:31:34'
      )
      OR (
        audio_clips.clip_type = 'news'
        AND audio_clips.publish_time > '2020-06-24 11:31:34'
      )
    )
    AND (
      c_categories.recommended = 'f'
    )
  GROUP BY
    collections.id
    ,c_categories.name
    ,admins.email), "valid_collections_with_points" AS (WITH "valid_collections" AS (
  SELECT
      DISTINCT valid_collections. *
      ,categories_with_points.points AS points
    FROM
      valid_collections LEFT OUTER JOIN categories_with_points
        ON valid_collections.category_id = categories_with_points.id
    WHERE
      (
        not_listened_clips_count > 0
      )
) SELECT
    "valid_collections" . *
  FROM
    "valid_collections"), "top_valid_collections" AS (WITH "valid_collections_with_points" AS (
  SELECT
      valid_collections_with_points. *
      ,ROW_NUMBER (
      ) OVER (
        PARTITION BY valid_collections_with_points.category_id
      ORDER BY
        valid_collections_with_points.publish_time DESC
      ) AS r_number
    FROM
      valid_collections_with_points
    WHERE
      (
        not_listened_clips_count > 0
      )
) SELECT
    "valid_collections_with_points" . *
  FROM
    "valid_collections_with_points"), "top_collections" AS (WITH "top_valid_collections" AS (
  SELECT
      top_valid_collections. *
    FROM
      top_valid_collections
    WHERE
      (
        top_valid_collections.r_number <= 1
      )
    ORDER BY
      top_valid_collections.points DESC
      ,top_valid_collections.publish_time DESC
      ,top_valid_collections.not_listened_clips_count DESC LIMIT 3
) SELECT
    "top_valid_collections" . *
  FROM
    "top_valid_collections"), "other_collections" AS (WITH "valid_collections" AS (
  SELECT
      valid_collections. *
      ,0 AS points
      ,0 AS r_number
    FROM
      valid_collections
    WHERE
      (
        valid_collections.id NOT IN (
          SELECT
              id
            FROM
              top_collections
        )
      )
    ORDER BY
      not_listened_clips_count DESC
      ,publish_time DESC
) SELECT
    "valid_collections" . *
  FROM
    "valid_collections") SELECT  top_collections.* FROM top_collections UNION ALL SELECT other_collections.* FROM other_collections LIMIT 20 OFFSET 0):
  app/presenters/api/collections_presenter.rb:11:in `as_json'
  app/controllers/api/base_controller.rb:29:in `respond'
  app/controllers/api/v2/categories_controller.rb:8:in `home'
```

**Comment by jdelporte** [comment]
Hi again,
For the first issue, is the method join_association some code of yours?  or from some other gems (like https://rubygems.org/gems/arel-helpers) that modify the AST and might conflict with other gems?
For your second issue, as you are using plain SQL query inside the scope I have trouble to see how it can be related to ArelExtensions. Plus there is no version 1.8.0 of our gem (https://rubygems.org/gems/arel_extensions/versions), so I am pretty confused.

**Comment by mithucste30** [comment]
@jdelporte sorry for the late reply, this issue was created when-ever i added `pp_sql` gem.
