### ISSUE TITLE
release 1.2.26/v.2.0.23 with a CI red ?

### ISSUE THREAD

**Issue by shingara** [Faveod/arel-extensions#47]
Why do you release a gem 2.0.23 with a red ci on Postgresql ?

On commit : https://github.com/Faveod/arel-extensions/commit/10e6f418c167f956817d68d9748c8da86c222dac

The Github Action/CI report : 

https://github.com/Faveod/arel-extensions/runs/4380304716?check_suite_focus=true

```
..........................E

Error:
the to_sql visitor#test_0019_should be possible to use as on anything:
NameError: uninitialized constant Arel::TableAlias
    /home/runner/work/arel-extensions/arel-extensions/lib/arel_extensions.rb:207:in `as'
rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib:test" -I"/opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib" "/opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb" "test/visitors/test_to_sql.rb" ]

Tasks: TOP => test:to_sql
(See full trace by running task with --trace)
    /home/runner/work/arel-extensions/arel-extensions/test/visitors/test_to_sql.rb:292:in `block (2 levels) in <module:VisitorToSql>'

rails test home/runner/work/arel-extensions/arel-extensions/test/visitors/test_to_sql.rb:285

...S.........
```

**Comment by jdelporte** [comment]
Hi Cyril,
Sorry, some bad mishandling from me. 
Sincerely sorry for the inconvenience. Previous and next gems should work fine.
