### ISSUE TITLE
Conflict with ransack gem

### ISSUE THREAD

**Issue by dvandersluis** [Faveod/arel-extensions#9]
When trying to use the `ransack` gem with `arel-extensions` installed, I get an `ArgumentError`:

```
ArgumentError: wrong number of arguments (given 3, expected 1..2)
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/arel_extensions-1.1.0/lib/arel_extensions/predications.rb:9:in `matches'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/arel-9.0.0/lib/arel/predications.rb:213:in `block in grouping_any'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/arel-9.0.0/lib/arel/predications.rb:213:in `map'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/arel-9.0.0/lib/arel/predications.rb:213:in `grouping_any'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/arel-9.0.0/lib/arel/predications.rb:131:in `matches_any'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/adapters/active_record/ransack/nodes/condition.rb:33:in `public_send'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/adapters/active_record/ransack/nodes/condition.rb:33:in `format_predicate'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/adapters/active_record/ransack/nodes/condition.rb:19:in `block in arel_predicate'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/adapters/active_record/ransack/nodes/condition.rb:6:in `map'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/adapters/active_record/ransack/nodes/condition.rb:6:in `arel_predicate'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/visitor.rb:17:in `visit_Ransack_Nodes_Condition'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/visitor.rb:42:in `visit'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/visitor.rb:5:in `accept'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/adapters/active_record/ransack/visitor.rb:4:in `block in visit_and'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/adapters/active_record/ransack/visitor.rb:4:in `map'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/adapters/active_record/ransack/visitor.rb:4:in `visit_and'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/visitor.rb:24:in `visit_Ransack_Nodes_Grouping'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/visitor.rb:42:in `visit'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/visitor.rb:5:in `accept'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/adapters/active_record/context.rb:33:in `evaluate'
	from /Users/daniel/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ransack-2.1.0/lib/ransack/search.rb:36:in `result'
```

Looks to be because `ArelExtensions::Predications#matches` has two arguments, but in Arel 9.0.0, `Arel::Predications#matches` and `Arel::Predications#matches_any` (which ransack is using) have 3 arguments.

**Comment by jdelporte** [comment]
Hi Daniel,

Thanks you for reporting this issue. A new commit has been pushed on git to support Arel9.

Regards,
